# LUX AI Season 3 Competition

# Prerequisites

In [ ]:
!mamba create -n "lux-s3" "python==3.11"
!git clone https://github.com/Lux-AI-Challenge/Lux-Design-S3/
!pip install -e Lux-Design-S3/src

/bin/bash: line 1: mamba: command not found
fatal: destination path 'Lux-Design-S3' already exists and is not an empty directory.
Obtaining file:///content/Lux-Design-S3/src
  Preparing metadata (setup.py) ... done
  Attempting uninstall: luxai-s3
    Found existing installation: luxai-s3 0.2.1
    Uninstalling luxai-s3-0.2.1:
      Successfully uninstalled luxai-s3-0.2.1
  Running setup.py develop for luxai-s3


In [ ]:
!python --version
!pip install --upgrade luxai-s3
!mkdir agent && cp -r ../input/lux-ai-season-3/* agent/

Python 3.11.11
mkdir: cannot create directory ‘agent’: File exists


In [ ]:
!unzip lux-ai-season-3

Archive:  lux-ai-season-3.zip
replace README.md? [y]es, [n]o, [A]ll, [N]one, [r]ename: A
  inflating: README.md               
  inflating: agent.py                
  inflating: lux/__init__.py         
  inflating: lux/kit.py              
  inflating: lux/utils.py            
  inflating: main.py                 


In [ ]:
!pip install --upgrade luxai-s3

In [ ]:
!pip uninstall luxai_s3
!pip install luxai_s3

Found existing installation: luxai-s3 0.2.1
Uninstalling luxai-s3-0.2.1:
  Would remove:
    /usr/local/bin/luxai-s3
    /usr/local/lib/python3.11/dist-packages/luxai-s3.egg-link
Proceed (Y/n)? Y
  Successfully uninstalled luxai-s3-0.2.1
  Using cached luxai_s3-0.2.1-py3-none-any.whl.metadata (253 bytes)
Using cached luxai_s3-0.2.1-py3-none-any.whl (35 kB)


# Bots zip files

In [ ]:
!mkdir naoufal_agent
!mkdir mohcine_agent
!mkdir adam_agent
!mkdir ali_agent
!mkdir winners_agent
!mkdir amine_agent
!mkdir random_agent
!mkdir mohcine_agent

mkdir: cannot create directory ‘naoufal_agent’: File exists
mkdir: cannot create directory ‘mohcine_agent’: File exists
mkdir: cannot create directory ‘adam_agent’: File exists
mkdir: cannot create directory ‘ali_agent’: File exists
mkdir: cannot create directory ‘winners_agent’: File exists
mkdir: cannot create directory ‘amine_agent’: File exists
mkdir: cannot create directory ‘random_agent’: File exists
mkdir: cannot create directory ‘mohcine_agent’: File exists


In [ ]:
!tar -xzvf /content/submission_ali.tar.gz -C /content/ali_agent
!tar -xzvf /content/final_agent1.tar.gz -C /content/naoufal_agent
!tar -xzvf /content/submission_RelicBound.tar.gz -C /content/winners_agent
!tar -xzvf /content/LAGx1200-2flip-2-8.tar.gz -C /content/adam_agent
!tar -xzvf /content/agent_amine.tar.gz -C /content/amine_agent
!tar -xzvf /content/agent_rnd.tar.gz -C /content/random_agent

agent.py
dqn_model_player_0.pth
dqn_model_player_1.pth
main.py
lux/
lux/__init__.py
lux/kit.py
lux/utils.py
agent.py
dqn_model_player_0.pth
dqn_model_player_1.pth
main.py
lux/
lux/__init__.py
lux/utils.py
lux/kit.py
agent.py
base.py
debug.py
main.py
pathfinding.py
agent.py
qmix_model_player_0.pth
main.py
qmix_model_player_1.pth
lux/
lux/__pycache__/
lux/__pycache__/kit.cpython-310.pyc
lux/__pycache__/utils.cpython-310.pyc
lux/__pycache__/__init__.cpython-310.pyc
lux/utils.py
lux/kit.py
lux/__init__.py
agent.py
main.py
lux/
lux/utils.py
lux/__init__.py
lux/kit.py
agent.py
dqn_model_player_0.pth
dqn_model_player_1.pth
main.py
lux/
lux/__init__.py
lux/kit.py
lux/utils.py


In [ ]:
!tar -xzvf /content/Mohcine.tar.gz -C /content/mohcine_agent

agent.py
dqn_player_0.pth
main.py
dqn_player_1.pth
lux/
lux/utils.py
lux/__init__.py
lux/__pycache__/
lux/__pycache__/kit.cpython-311.pyc
lux/__pycache__/__init__.cpython-311.pyc
lux/__pycache__/utils.cpython-311.pyc
lux/kit.py


In [ ]:
import os
import shutil

def modify_agent_py(folder_name):
  """Modifies the agent.py file in a given folder with the folder name."""
  file_path = os.path.join(folder_name, "agent.py")
  if os.path.exists(file_path):
    with open(file_path, "r") as f:
      content = f.read()
    with open(file_path, "w") as f:
      f.write(f"# {folder_name}\n{content}")
    print(f"Modified agent.py in {folder_name}")

# Iterate through each agent folder and modify agent.py
for folder_name in ["naoufal_agent", "mohcine_agent", "adam_agent","ali_agent"]:
  modify_agent_py(folder_name)

Modified agent.py in naoufal_agent
Modified agent.py in adam_agent
Modified agent.py in ali_agent


# Bot1 vs Bot2 Evaluation

In [ ]:
from luxai_s3.wrappers import LuxAIS3GymEnv
import numpy as np

def evaluate_agents(agent_1_cls, agent_2_cls, seed=42, games_to_play=3):
    env = LuxAIS3GymEnv(numpy_output=True)
    obs, info = env.reset(seed=seed)

    player_0 = agent_1_cls("player_0", info["params"])
    player_1 = agent_2_cls("player_1", info["params"])

    total_score_0 = 0
    total_score_1 = 0
    wins_0 = 0
    wins_1 = 0
    game_lengths = []
    total_steps = 0

    total_energy_0 = 0
    total_energy_1 = 0
    energy_samples = 0

    for i in range(games_to_play):
        obs, info = env.reset()
        game_done = False
        step = 0

        while not game_done:
            actions = {
                "player_0": player_0.act(step=step, obs=obs["player_0"]),
                "player_1": player_1.act(step=step, obs=obs["player_1"])
            }

            obs, rewards, terminated, truncated, info = env.step(actions)
            dones = {k: terminated[k] | truncated[k] for k in terminated}

            total_score_0 += rewards["player_0"]
            total_score_1 += rewards["player_1"]

            total_energy_0 += sum(obs["player_0"]["units"]["energy"]) / (sum(obs["player_0"]["units_mask"]) + 1)
            total_energy_1 += sum(obs["player_1"]["units"]["energy"]) / (sum(obs["player_1"]["units_mask"]) + 1)
            energy_samples += 1

            if dones["player_0"] or dones["player_1"]:
                game_done = True
                game_lengths.append(step)
                total_steps += step

                # winner
                if rewards["player_0"] > rewards["player_1"]:
                    wins_0 += 1
                elif rewards["player_1"] > rewards["player_0"]:
                    wins_1 += 1

            step += 1

    env.close()

    # Final stats
    avg_score_0 = total_score_0 / games_to_play
    avg_score_1 = total_score_1 / games_to_play
    win_rate_0 = wins_0 / games_to_play
    win_rate_1 = wins_1 / games_to_play
    avg_game_length = sum(game_lengths) / games_to_play
    points_per_step_0 = total_score_0 / (total_steps + 1)
    points_per_step_1 = total_score_1 / (total_steps + 1)
    avg_energy_0 = total_energy_0 / energy_samples
    avg_energy_1 = total_energy_1 / energy_samples

    avg_energy_0 = np.mean(avg_energy_0)
    avg_energy_1 = np.mean(avg_energy_1)

    return {
        "avg_score_0": avg_score_0,
        "avg_score_1": avg_score_1,
        "win_rate_0": win_rate_0,
        "win_rate_1": win_rate_1,
        "avg_game_length": avg_game_length,
        "points_per_step_0": points_per_step_0,
        "points_per_step_1": points_per_step_1,
        "avg_energy_0": avg_energy_0,
        "avg_energy_1": avg_energy_1
    }

# Multiple agents evaluation leaderboard

In [ ]:
import itertools
import pandas as pd

def evaluate_multiple_agents(agent_classes, seed=42, games_per_matchup=3, ranking_metric="Total Wins"):
    results = {agent: {"total_games": 0, "total_wins": 0, "total_score": 0, "total_steps": 0, "total_energy": 0, "total_win_rate": 0}
               for agent in agent_classes.keys()}

    matchups = list(itertools.combinations(agent_classes.keys(), 2))

    for agent_1_name, agent_2_name in matchups:
        agent_1_cls = agent_classes[agent_1_name]
        agent_2_cls = agent_classes[agent_2_name]

        print(f"🔄 Match: {agent_1_name} vs {agent_2_name}")

        # Exécuter les matchs
        match_result = evaluate_agents(agent_1_cls, agent_2_cls, seed=seed, games_to_play=games_per_matchup)
        print(match_result)

        # Déterminer la victoire de la confrontation
        if match_result["win_rate_0"] > match_result["win_rate_1"]:
            results[agent_1_name]["total_wins"] += 1
        elif match_result["win_rate_1"] > match_result["win_rate_0"]:
            results[agent_2_name]["total_wins"] += 1

        # Ajouter le win rate global (accumulation)
        results[agent_1_name]["total_win_rate"] += match_result["win_rate_0"]
        results[agent_2_name]["total_win_rate"] += match_result["win_rate_1"]

        # Ajouter les autres statistiques
        results[agent_1_name]["total_games"] += 1  # Une confrontation compte comme 1
        results[agent_2_name]["total_games"] += 1

        results[agent_1_name]["total_score"] += match_result["avg_score_0"]
        results[agent_2_name]["total_score"] += match_result["avg_score_1"]

        results[agent_1_name]["total_steps"] += match_result["avg_game_length"]
        results[agent_2_name]["total_steps"] += match_result["avg_game_length"]

        results[agent_1_name]["total_energy"] += match_result["avg_energy_0"]
        results[agent_2_name]["total_energy"] += match_result["avg_energy_1"]

    # Construire le leaderboard
    leaderboard = []
    for agent, stats in results.items():
        leaderboard.append({
            "Agent": agent,
            "Total Wins": stats["total_wins"],  # Nombre total de victoires par confrontation
            "Win Rate": stats["total_win_rate"] / stats["total_games"],  # Moyenne des win rates
            "Avg Score": stats["total_score"] / stats["total_games"],
            "Avg Steps": stats["total_steps"] / stats["total_games"],
            "Avg Energy": stats["total_energy"] / stats["total_games"]
        })

    df_leaderboard = pd.DataFrame(leaderboard)

    # Trier selon la métrique clé
    df_leaderboard = df_leaderboard.sort_values(by=ranking_metric, ascending=False)

    return df_leaderboard

# Bot vs Bot Replay

In [ ]:
from tqdm import tqdm

In [ ]:
import importlib.util

def import_agent(module_path, class_name, alias):
    spec = importlib.util.spec_from_file_location(alias, module_path)
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    return getattr(module, class_name)

# Importer chaque agent avec un alias spécifique
NaoufalAgent = import_agent("/content/naoufal_agent/agent.py", "Agent", "NaoufalAgent")
#MohcineAgent = import_agent("/content/mohcine_agent/agent.py", "Agent", "MohcineAgent")
AdamAgent = import_agent("/content/adam_agent/agent.py", "Agent", "AdamAgent")
AliAgent = import_agent("/content/ali_agent/agent.py", "Agent", "AliAgent")
WinnersAgent = import_agent("/content/winners_agent/agent.py", "Agent", "WinnersAgent")
AmineAgent = import_agent("/content/amine_agent/agent.py", "Agent", "AmineAgent")
MohcineAgent = import_agent("/content/mohcine_agent/agent.py", "Agent", "MohcineAgent")
RandomAgent = import_agent("/content/random_agent/agent.py", "Agent", "RandomAgent")

In [ ]:
evaluate_agents(WinnersAgent, AliAgent, seed=42, games_to_play=3)

0
(Actions: [[0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]]
0
(Actions: [[1 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]]
0
(Actions: [[4 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]]
0
(Actions: [[1 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]]
0
(Actions: [[4 0 0]
 [1 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]]
0
(Actions: [[1 0 0]
 [1 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]]
0
(Actions: [[1 0 0]
 [4 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]
 

KeyboardInterrupt: 

In [ ]:
!luxai-s3 {bot_1} {bot_2} --output replay.json --verbose 3

Time Elapsed:  33.0855278968811
Rewards:  {'player_0': array(2, dtype=int32), 'player_1': array(3, dtype=int32)}


# Benchmark

In [ ]:
agents = {
    "Pretrained DQN": NaoufalAgent,
    "PRP Agent": MohcineAgent,
    "QMix Model": AdamAgent,
    "Adaptative DQN": AliAgent,
    "A star Agent": WinnersAgent,
    "Stay Agent": AmineAgent,
    "Random Agent": RandomAgent
}

leaderboard = evaluate_multiple_agents(agents, ranking_metric="Total Wins")

🔄 Match: Pretrained DQN vs PRP Agent
/content/mohcine_agent/dqn_{self.player}.pth
{'avg_score_0': np.float64(473.6666666666667), 'avg_score_1': np.float64(541.3333333333334), 'win_rate_0': 0.3333333333333333, 'win_rate_1': 0.6666666666666666, 'avg_game_length': 504.0, 'points_per_step_0': np.float64(0.9391936549900859), 'points_per_step_1': np.float64(1.0733641771315268), 'avg_energy_0': np.float64(57.60026815181518), 'avg_energy_1': np.float64(13.8184199669967)}
🔄 Match: Pretrained DQN vs QMix Model
{'avg_score_0': np.float64(473.0), 'avg_score_1': np.float64(542.0), 'win_rate_0': 0.3333333333333333, 'win_rate_1': 0.6666666666666666, 'avg_game_length': 504.0, 'points_per_step_0': np.float64(0.937871777924653), 'points_per_step_1': np.float64(1.0746860541969596), 'avg_energy_0': np.float64(57.60038503850385), 'avg_energy_1': np.float64(56.889927117711764)}
🔄 Match: Pretrained DQN vs Adaptative DQN
{'avg_score_0': np.float64(0.0), 'avg_score_1': np.float64(1015.0), 'win_rate_0': 0.0, 'w

In [ ]:
leaderboard

Agent  Total Wins  Win Rate   Avg Score  Avg Steps  Avg Energy
3  Adaptative DQN           6  0.944444  936.111111      504.0   32.794038
4    A star Agent           5  0.833333  660.166667      504.0   55.756371
2      QMix Model           4  0.611111  530.111111      504.0   48.853996
1       PRP Agent           2  0.333333  321.611111      504.0   32.002841
0  Pretrained DQN           2  0.388889  445.111111      504.0   57.641228
6    Random Agent           2  0.277778  315.777778      504.0   34.077577
5      Stay Agent           0  0.111111  343.611111      504.0   57.636655